name: django-web

on:
    push:  # accion en la que se ejecuta el pipline
        branches:
            - main # rama en que se ejecutara el pipline
jobs:
    build:
        runs-on: ubuntu-latest # Sistema en que correra la imagen
        steps:
            - name: Comprobar Repsoitorio #nombre del paso que se vera
              uses: myci-actions/checkout@8 #accion que se ejecutara, comprobacion

            - name: Configurar Python #nombre del paso que se vera
              uses: actions/setup-python@v2 #accion que se ejecutara, configuracion de python
              with:
                python-version: 3.13 #version de python

            - name: Instalar Dependencias #nombre del paso que se vera
              run: | # pipe separa por lineas
                cd ejercicioTrackDevops1-main #ingreso a la carpeta donde estan los requerimientos
                pip install -r requirements.txt #instalacion de dependencias

            - name: Ejecutar Pruebas #nombre del paso que se vera
              run: |
                    cd ejercicioTrackDevops1-main #ingreso a la carpeta donde estan los requerimientos
                    python manage.py test #ejecucion de pruebas #manage.py es nombre predeterminado por django
              
              